<?php

    use Icinga\Web\Url;

    /** @var \Icinga\Web\View $this */
    /** @var \Icinga\Web\Widget\FilterEditor $filterEditor */
    /** @var \Icinga\Module\Monitoring\DataView\DataView $services */
    /** @var \Icinga\Web\Url $hostBaseUrl */
    /** @var \Icinga\Web\Url $serviceBaseUrl */

    use Icinga\Application\Config;

    $config = Config::module('inventoriz');
    $server_url = $config->get('inventoriz', 'url');
    $inventoriz_user = $config->get('inventoriz', 'user');
    $inventoriz_password = $config->get('inventoriz', 'password');

    // Requirements
    global $config;

    // Работаем через прокси, для запросов на прямую убрать: /icingaweb2/proxy.php?url=
    $config = array(
        'inventoriz_url' => '/icingaweb2/proxy.php?url=' . $server_url,
        'inventoriz_user' => $inventoriz_user,
        'inventoriz_password' => $inventoriz_password
    );
    


/**
<?php if (! $compact): ?>
<div class="controls">
    <?= $tabs ?>
</div>
<?php endif ?>
*/
        
?>









<div class="content">
    <div class="row" id="inventoriz-index" data-api-url="<?php echo $config['inventoriz_url']; ?>">
        <div class="col-xs-24" style="width: 100%;">
            <section class="inventoriz-section">
                <header class="section-header">
                    <h1 class="section-title">
                        Dashboard
                    </h1>
                </header>
    
                <div class="row">
                    <div class="col-md-12" style="width: 50%;">
                        <div class="chart_wrap">
                            <div id="chartManufacturers" style="width: 100%; height: 360px;"></div>
                        </div>
                    </div>
                    <div class="col-md-12" style="width: 50%;">
                        <div class="chart_wrap">
                            <div id="chartOS" style="width: 100%; height: 360px;"></div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" style="width: 50%;">
                        <div class="chart_wrap">
                            <div id="chartCPU" style="width: 100%; height: 360px;"></div>
                        </div>
                    </div>
                    <div class="col-md-12" style="width: 50%;">
                        <div class="chart_wrap">
                            <div id="chartUpdated" style="width: 100%; height: 360px;"></div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-24" style="width: 100%;">
                        <div class="table-responsive">
                            <table class="table" id="tableComputers" style="width: 100%;">
                                <thead>
                                <tr>
                                    <th>Имя</th>
                                    <th>Последний опрос</th>
                                    <th>Операционная система</th>
                                    <th>Процессор</th>
                                    <th>Оперативная память</th>
                                </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>



            </section>
        </div>
    </div>
</div>






<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script>
    $(document).ready(function () {
        setTimeout(function(){
            onLoadIndexPage();
        }, 1000);
    });
</script>
