<?php

use Icinga\Web\Url;

/** @var \Icinga\Web\View $this */
/** @var \Icinga\Web\Widget\FilterEditor $filterEditor */
/** @var \Icinga\Module\Monitoring\DataView\DataView $services */
/** @var \Icinga\Web\Url $hostBaseUrl */
/** @var \Icinga\Web\Url $serviceBaseUrl */

use Icinga\Application\Config;

$config = Config::module('inventoriz');
$server_url = $config->get('inventoriz', 'url');

// Requirements
global $config;

$config = array(
  'inventoriz_url' => $server_url,
);

?>

<div class="controls">
<?= $this->tabs ?>
</div>


<div class="content">
    <div class="row">
        <div class="col-xs-24">
            <section class="section">
                <header class="section-header">
                    <h1 class="section-title">
                    <?php echo $this->translate('Hardware Information') ?>
                    </h1>
                </header>
    
                <div class="row">
                    <div class="col-md-24">
                        <div class="computer-tree" id="tree"></div>
                        <div id="statusline"></div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>





<script>
    $(document).ready(function () {

        var inventorizUrl = "<?php echo $config['inventoriz_url']; ?>";
        var computerName = "<?php echo $treehost; ?>";
        var computerId = "";

        $.ajax({
            type: "GET",
            url: inventorizUrl + '/api/v1/computer-name',
            data: jQuery.param({ 'name': computerName}),
            success: function (data) {
                // console.log(data);
                computerId = data.id;
                if (typeof(computerId) != "undefined" && computerId !== null) {
                    computerId = data.id;
                    renderComputerTree(computerId);
                } else {
                    $('#tree').html('<p>No data</p>');
                }
            },
            error: function (jqXHR, text, error) {
                $('#tree').html('<p>' + error + '</p>');
                console.log(error);
            }
        });
   

        function renderComputerTree(computerId){
            $('#tree').fancytree({
                source: {url: inventorizUrl + '/api/v1/computers/' + computerId + '/properties'},
                tooltip: true,
                iconTooltip: function(event, data) {
                    return data.typeInfo.iconTooltip;
                },
                icon: function(event, data) {
                    if (data.node.icon) {
                        return 'img/inventoriz/icons/' + data.node.icon;
                    }
                },

            });
        }

    });

</script>