<?php

use Icinga\Web\Url;

/** @var \Icinga\Web\View $this */
/** @var \Icinga\Web\Widget\FilterEditor $filterEditor */
/** @var \Icinga\Module\Monitoring\DataView\DataView $services */
/** @var \Icinga\Web\Url $hostBaseUrl */
/** @var \Icinga\Web\Url $serviceBaseUrl */

use Icinga\Application\Config;

$config = Config::module('inventoriz');
$server_url = $config->get('inventoriz', 'url');
$inventoriz_user = $config->get('inventoriz', 'user');
$inventoriz_password = $config->get('inventoriz', 'password');

// Requirements
global $config;

$config = array(
  'inventoriz_url' => $server_url,
  'inventoriz_user' => $inventoriz_user,
  'inventoriz_password' => $inventoriz_password
);


?>





<div class="controls">
<?= $this->tabs ?>
</div>


<div class="content">
    <div class="row">
        <div class="col-xs-24">
            <section class="section">
                <header class="section-header">
                    <h1 class="section-title">
                    <?php echo $this->translate('Hardware Information') ?>
                    </h1>
                </header>
    
                <div class="row">
                    <div class="col-md-24">
                        <div class="computer-tree" id="tree"></div>
                        <div id="statusline"></div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>








<script>
    $(document).ready(function () {

        // Работаем через прокси, для запросов на прямую убрать: /icingaweb2/proxy.php?url=
        var inventorizUrl = "/icingaweb2/proxy.php?url=<?php echo $config['inventoriz_url']; ?>";
        var computerName = "<?php echo $treehost; ?>";
        var computerId = "";

        var auth_token;


        if (localStorage.token) {

            auth_token = localStorage.token;

            $.ajax({
                type: 'GET',
                url: inventorizUrl + '/api/v1/computer-name?name=' + computerName,
                // data: jQuery.param({ 'name': computerName }),
                headers: {
                    'Authorization': 'Bearer ' + auth_token
                },
                success: function (data) {
                    // console.log(data);
                    computerId = data.id;
                    if (typeof(computerId) != 'undefined' && computerId !== null) {
                        computerId = data.id;
                        renderComputerTree(computerId, auth_token);
                    } else {
                        console.log(data);
                        $('#tree').html('<p>No data</p>');
                    }
                },
                error: function (jqXHR, text, error) {
                    $('#tree').html('<p>' + error + '</p>');
                    console.log(error);
                }
            });

        } else {

            console.log('При загрузке страницы не обнаружен токен для авторизации!');

            // loginForm = '<form id="inventoriz-login-form">' +
            //         '<div class="form-group">' +
            //             '<label for="email">Имя пользователя</label>' +
            //             '<input type="email" class="form-control" id="email" name="email" placeholder="Имя пользователя" required="">' +
            //         '</div>' +
            //         '<div class="form-group">' +
            //             '<label for="password">Пароль</label>' +
            //             '<input type="password" class="form-control" id="password" name="password" placeholder="Пароль" required="">' +
            //         '</div>' +
            //         '<div class="form-group">' +
            //             '<button type="submit" class="btn btn-primary">Вход</button>' +
            //             '<button type="button" class="btn btn-info" data-dismiss="modal">Отмена</button>' +
            //         '</div>' +
            //     '</form>';

            // $('#tree').html(loginForm);


            $('#tree').html('<p>Unauthorized</p>');
        }




        function renderComputerTree(computerId, auth_token){
            // console.log(auth_token);
            $('#tree').fancytree({
                ajax: { type: 'GET',
                    beforeSend: function (xhr) {
                        if (auth_token) {
                            xhr.setRequestHeader('Authorization', 'Bearer ' + auth_token);
                        }
                    }
                },
                source: { url: inventorizUrl + '/api/v1/computers/' + computerId + '/hardware' },
                tooltip: true,
                iconTooltip: function(event, data) {
                    return data.typeInfo.iconTooltip;
                },
                icon: function(event, data) {
                    if (data.node.icon) {
                        return 'img/inventoriz/icons/' + data.node.icon;
                    }
                },

            });
        }


   
    });



</script>














<?php
/*
// Предыдущая версия с авторизацией

            var json_url_login = inventorizUrl + '/api/login';
            $.ajax({
                type: 'POST',
                url: json_url_login,
                headers: {
                    'Content-type': 'application/x-www-form-urlencoded; charset=UTF-8'
                },
                data: jQuery.param({ 'email': '<?php echo $config['inventoriz_user']; ?>', 'password': '<?php echo $config['inventoriz_password']; ?>'}),
                success: function (data) {
                    // console.log(data);
                    auth_token = data.token;

                    auth_token = localStorage.token;

                    $.ajax({
                        type: 'GET',
                        url: inventorizUrl + '/api/v1/computer-name?name=' + computerName,
                        // data: jQuery.param({ 'name': computerName }),
                        headers: {
                            'Authorization': 'Bearer ' + auth_token
                        },
                        success: function (data) {
                            // console.log(data);
                            computerId = data.id;
                            if (typeof(computerId) != 'undefined' && computerId !== null) {
                                computerId = data.id;
                                renderComputerTree(computerId, auth_token);
                            } else {
                                console.log(data);
                                $('#tree').html('<p>No data</p>');
                            }
                        },
                        error: function (jqXHR, text, error) {
                            $('#tree').html('<p>' + error + '</p>');
                            console.log(error);
                        }
                    });


                },
                error: function (jqXHR, text, error) {
                    console.log(error);
                }
            });


*/

?>